# Generated by Django 6.1 on 2026-08-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Society Admin'), ('COMMITTEE', 'Committee Member'), ('RESIDENT', 'Resident'), ('SECURITY', 'Security Guard'), ('STAFF', 'Staff')], default='RESIDENT', max_length=20, verbose_name='role'),
        ),
    ]
