from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial=True
    dependencies=[('core','0001_initial'),migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations=[
        migrations.CreateModel(name='Vehicle',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('owner_name',models.CharField(max_length=120)),('vehicle_number',models.CharField(max_length=20,unique=True)),('vehicle_type',models.CharField(choices=[('CAR','Car'),('BIKE','Bike'),('OTHER','Other')],default='CAR',max_length=30)),('parking_slot',models.CharField(blank=True,max_length=30)),('photo',models.ImageField(blank=True,null=True,upload_to='vehicles/')),('is_active',models.BooleanField(default=True)),('flat',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='vehicles',to='core.flat'))]),
        migrations.CreateModel(name='VendorAMC',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('service_name',models.CharField(max_length=120)),('vendor_name',models.CharField(max_length=150)),('contact_person',models.CharField(blank=True,max_length=120)),('phone',models.CharField(blank=True,max_length=20)),('amount',models.DecimalField(decimal_places=2,default=0,max_digits=12)),('start_date',models.DateField()),('renewal_date',models.DateField()),('document',models.FileField(blank=True,null=True,upload_to='vendor_amc/')),('notes',models.TextField(blank=True)),('is_active',models.BooleanField(default=True))],options={'ordering':['renewal_date']}),
        migrations.CreateModel(name='Parcel',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('recipient_name',models.CharField(max_length=120)),('courier_name',models.CharField(blank=True,max_length=100)),('tracking_number',models.CharField(blank=True,max_length=100)),('photo',models.ImageField(blank=True,null=True,upload_to='parcels/')),('status',models.CharField(choices=[('RECEIVED','Received at Gate'),('NOTIFIED','Resident Notified'),('COLLECTED','Collected')],default='RECEIVED',max_length=12)),('received_at',models.DateTimeField(auto_now_add=True)),('collected_at',models.DateTimeField(blank=True,null=True)),('flat',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='parcels',to='core.flat')),('received_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='MoveRequest',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('move_type',models.CharField(choices=[('MOVE_IN','Move In'),('MOVE_OUT','Move Out')],max_length=10)),('requested_date',models.DateField()),('status',models.CharField(choices=[('REQUESTED','Requested'),('APPROVED','Approved'),('COMPLETED','Completed'),('REJECTED','Rejected')],default='REQUESTED',max_length=12)),('document',models.FileField(blank=True,null=True,upload_to='move_requests/')),('notes',models.TextField(blank=True)),('created_at',models.DateTimeField(auto_now_add=True)),('flat',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='move_requests',to='core.flat')),('requested_by',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='Expense',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('title',models.CharField(max_length=150)),('category',models.CharField(choices=[('UTILITIES','Utilities'),('REPAIR','Repair & Maintenance'),('SALARY','Salary'),('VENDOR','Vendor'),('EVENT','Event'),('OTHER','Other')],default='OTHER',max_length=20)),('amount',models.DecimalField(decimal_places=2,max_digits=12)),('expense_date',models.DateField()),('vendor',models.CharField(blank=True,max_length=150)),('receipt',models.ImageField(blank=True,null=True,upload_to='expense_receipts/')),('notes',models.TextField(blank=True)),('created_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to=settings.AUTH_USER_MODEL))],options={'ordering':['-expense_date']})]
