from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('operations','0001_initial'), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name='DomesticWorker', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=120)),('service_type',models.CharField(choices=[('MAID','Maid'),('DRIVER','Driver'),('COOK','Cook'),('CLEANER','Cleaner'),('TUTOR','Tutor'),('OTHER','Other')],default='MAID',max_length=20)),('phone',models.CharField(blank=True,max_length=20)),('id_number',models.CharField(blank=True,max_length=80)),('photo',models.ImageField(blank=True,null=True,upload_to='domestic_workers/')),('id_document',models.FileField(blank=True,null=True,upload_to='domestic_worker_docs/')),('police_verified',models.BooleanField(default=False)),('is_active',models.BooleanField(default=True)),('flats',models.ManyToManyField(blank=True,related_name='domestic_workers',to='core.flat'))]),
        migrations.CreateModel(name='SocietyAsset', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=150)),('category',models.CharField(choices=[('CCTV','CCTV'),('LIFT','Lift'),('PUMP','Pump'),('GENERATOR','Generator'),('FIRE','Fire Safety'),('GYM','Gym Equipment'),('OTHER','Other')],default='OTHER',max_length=20)),('asset_code',models.CharField(max_length=60,unique=True)),('location',models.CharField(blank=True,max_length=150)),('purchase_date',models.DateField(blank=True,null=True)),('warranty_until',models.DateField(blank=True,null=True)),('next_service_date',models.DateField(blank=True,null=True)),('document',models.FileField(blank=True,null=True,upload_to='assets/')),('is_active',models.BooleanField(default=True))]),
        migrations.CreateModel(name='EmergencyContact', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=140)),('category',models.CharField(choices=[('AMBULANCE','Ambulance'),('HOSPITAL','Hospital'),('POLICE','Police'),('FIRE','Fire Brigade'),('ELECTRICIAN','Electrician'),('PLUMBER','Plumber'),('OTHER','Other')],max_length=20)),('phone',models.CharField(max_length=25)),('secondary_phone',models.CharField(blank=True,max_length=25)),('notes',models.CharField(blank=True,max_length=220)),('is_active',models.BooleanField(default=True))],options={'ordering':['category','name']}),
        migrations.CreateModel(name='SocietyEvent', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('title',models.CharField(max_length=160)),('event_date',models.DateTimeField()),('venue',models.CharField(blank=True,max_length=160)),('description',models.TextField(blank=True)),('poster',models.ImageField(blank=True,null=True,upload_to='events/')),('registration_required',models.BooleanField(default=False)),('contribution_amount',models.DecimalField(decimal_places=2,default=0,max_digits=10)),('is_active',models.BooleanField(default=True))],options={'ordering':['event_date']}),
        migrations.CreateModel(name='Poll', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('question',models.CharField(max_length=220)),('description',models.TextField(blank=True)),('closes_at',models.DateTimeField(blank=True,null=True)),('is_active',models.BooleanField(default=True)),('created_at',models.DateTimeField(auto_now_add=True)),('created_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='SocietyMeeting', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('title',models.CharField(max_length=160)),('meeting_date',models.DateTimeField()),('venue',models.CharField(blank=True,max_length=160)),('agenda',models.TextField(blank=True)),('minutes',models.TextField(blank=True)),('attachment',models.FileField(blank=True,null=True,upload_to='meetings/')),('created_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to=settings.AUTH_USER_MODEL))],options={'ordering':['-meeting_date']}),
        migrations.CreateModel(name='LostFoundItem', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('item_type',models.CharField(choices=[('LOST','Lost'),('FOUND','Found')],max_length=10)),('title',models.CharField(max_length=140)),('description',models.TextField(blank=True)),('location',models.CharField(blank=True,max_length=140)),('photo',models.ImageField(blank=True,null=True,upload_to='lost_found/')),('status',models.CharField(choices=[('OPEN','Open'),('CLAIMED','Claimed'),('CLOSED','Closed')],default='OPEN',max_length=10)),('reported_at',models.DateTimeField(auto_now_add=True)),('reported_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to=settings.AUTH_USER_MODEL))],options={'ordering':['-reported_at']}),
        migrations.CreateModel(name='CertificateRequest', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('request_type',models.CharField(choices=[('NOC','NOC'),('ADDRESS','Address Proof'),('TENANT','Tenant Verification Letter'),('PARKING','Parking Certificate'),('OTHER','Other')],max_length=20)),('purpose',models.TextField(blank=True)),('supporting_document',models.FileField(blank=True,null=True,upload_to='certificate_requests/')),('status',models.CharField(choices=[('PENDING','Pending'),('APPROVED','Approved'),('REJECTED','Rejected'),('ISSUED','Issued')],default='PENDING',max_length=12)),('requested_at',models.DateTimeField(auto_now_add=True)),('flat',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='certificate_requests',to='core.flat')),('requested_by',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='certificate_requests',to=settings.AUTH_USER_MODEL))],options={'ordering':['-requested_at']}),
        migrations.CreateModel(name='StaffAttendance', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('check_in',models.DateTimeField(auto_now_add=True)),('check_out',models.DateTimeField(blank=True,null=True)),('gate_note',models.CharField(blank=True,max_length=200)),('recorded_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to=settings.AUTH_USER_MODEL)),('worker',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='attendance',to='operations.domesticworker'))],options={'ordering':['-check_in']}),
        migrations.CreateModel(name='PollOption', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('label',models.CharField(max_length=120)),('poll',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='options',to='operations.poll'))]),
        migrations.CreateModel(name='PollVote', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('voted_at',models.DateTimeField(auto_now_add=True)),('option',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='votes',to='operations.polloption')),('poll',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='votes',to='operations.poll')),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to=settings.AUTH_USER_MODEL))]),
        migrations.AddConstraint(model_name='pollvote',constraint=models.UniqueConstraint(fields=('poll','user'),name='one_vote_per_user_per_poll')),
    ]
