# Generated by Django 6.1 on 2026-08-09 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('purpose', models.CharField(choices=[('GUEST', 'Guest'), ('DELIVERY', 'Delivery'), ('CAB', 'Cab/Taxi'), ('SERVICE', 'Service/Repair'), ('VENDOR', 'Vendor'), ('OTHER', 'Other')], default='GUEST', max_length=15)),
                ('vehicle_number', models.CharField(blank=True, max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='visitor_photos/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('DENIED', 'Denied'), ('CHECKED_IN', 'Checked In'), ('CHECKED_OUT', 'Checked Out')], default='PENDING', max_length=15)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_visitors', to=settings.AUTH_USER_MODEL)),
                ('visiting_flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='core.flat')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
